# : Manager [[[

[manager]
cwd = { fg = "#f1dedd" }

# Tab
tab_active = { fg = "#571d1c", bg = "#ffb3ae", bold = true }
tab_inactive = { fg = "#ffdad7", bg = "#3b0809" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ffb841", bg = "#ffb841" }
marker_cut = { fg = "#ffdea7", bg = "#ffdea7" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e2c28c", bg = "#e2c28c" }

# Count
count_copied = { fg = "#271900", bg = "#ffdea7" }
count_cut = { fg = "#271900", bg = "#ffdea7" }
count_selected = { fg = "#571d1c", bg = "#e2c28c" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb3ae" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#571d1c", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#ffb3ae", fg = "#571d1c", bold = true }
normal_alt  = { bg = "#534342", fg = "#d8c2c0" }

# Select mode
select_main = { bg = "#e7bdb9", fg = "#442928", bold = true }
select_alt  = { bg = "#534342", fg = "#d8c2c0" }

# Unset mode
unset_main = { bg = "#e2c28c", fg = "#402d04", bold = true }
unset_alt  = { bg = "#534342", fg = "#d8c2c0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#ffb3ae", bg = "#423736" }
progress_error = { fg = "#ffb4ab", bg = "#423736" }

# Permissions
permissions_t = { fg = "#c05247" }
permissions_w = { fg = "#aa7b2b" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ffa50e" }
permissions_s = { fg = "#ff4c3e" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#ffb3ae" }
active = { fg = "#e2c28c", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb3ae" }
value = { fg = "#f1dedd" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#ffb3ae", bg = "#571d1c" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#ffb3ae" }
title = {}
hovered = { fg = "#ffdea7", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#423736" }
cand = { fg = "#ffb3ae" }
rest = { fg = "#571d1c" }
desc = { fg = "#f1dedd" }
separator = " ▶ "
separator_style = { fg = "#f1dedd" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#f1dedd" }
run = { fg = "#f1dedd" }
footer = { fg = "#442928", bg = "#e7bdb9" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e2c28c" }
title_warn = { fg = "#ffb3ae" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#f1dedd" },
    { name = "*/", fg = "#ffb3ae" },
]

# : ]]]