# Autostart

# Waybar
exec-once = waybar

# # Quickshell
# exec-once = qs -c Noctalia

# OpenRGB
exec-once = openrgb

# swww
exec-once = swww-daemon

# hyprsunset
exec-once = hyprsunset

# hypridle
exec-once = hypridle
